name: Lint UI
run-name: Lint UI - ${{ github.run_id }} - @${{ github.actor }}

on:
  pull_request:
    paths:
      - 'web/**'
  merge_group:
    paths:
      - 'web/**'

jobs:
  lint:
    name: Prettier, ESLint, & TSC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout OSS Teleport
        uses: actions/checkout@v4

      - name: Print Node version
        run: |
          node --version

      - name: Install Yarn dependencies
        run: yarn --frozen-lockfile

      - name: Run Type Check
        run: yarn type-check

      - name: Run lint
        run: yarn lint

      - name: Run Storybook smoke test
        run: yarn storybook-smoke-test
